# Configuration for JetHexa controllers

# Joint State Controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers for each joint
# Adding explicit, symmetrical PID gains
# LF Leg
coxa_joint_LF_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_LF
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_LF_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_LF
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_LF_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_LF
  pid: {p: 100.0, i: 0.1, d: 1.0}

# LM Leg
coxa_joint_LM_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_LM
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_LM_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_LM
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_LM_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_LM
  pid: {p: 100.0, i: 0.1, d: 1.0}

# LR Leg
coxa_joint_LR_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_LR
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_LR_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_LR
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_LR_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_LR
  pid: {p: 100.0, i: 0.1, d: 1.0}

# RF Leg
coxa_joint_RF_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_RF
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_RF_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_RF
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_RF_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_RF
  pid: {p: 100.0, i: 0.1, d: 1.0}

# RM Leg
coxa_joint_RM_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_RM
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_RM_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_RM
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_RM_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_RM
  pid: {p: 100.0, i: 0.1, d: 1.0}

# RR Leg
coxa_joint_RR_position_controller:
  type: position_controllers/JointPositionController
  joint: coxa_joint_RR
  pid: {p: 100.0, i: 0.1, d: 1.0}
femur_joint_RR_position_controller:
  type: position_controllers/JointPositionController
  joint: femur_joint_RR
  pid: {p: 100.0, i: 0.1, d: 1.0}
tibia_joint_RR_position_controller:
  type: position_controllers/JointPositionController
  joint: tibia_joint_RR
  pid: {p: 100.0, i: 0.1, d: 1.0} 