<?xml version="1.0" encoding="ASCII" ?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- parameters -->
    <xacro:property name="my_pi" value="3.1415926535897931"/>
    <xacro:property name="body_length_x" value="0.3556"/>
    <xacro:property name="body_length_y" value="0.165"/>
    <xacro:property name="coxa_length" value="0.04505032"/>
    <xacro:property name="femur_length" value="0.07703"/>

    <!-- Joint properties -->
    <xacro:property name="joint_lower_limit" value="-${3.14}" />
    <xacro:property name="joint_upper_limit" value="${3.14}" />
    <xacro:property name="joint_effort" value="100.0" />
    <xacro:property name="joint_velocity" value="10.0" />

    <!-- Leg macro -->
    <xacro:macro name="leg" params="prefix side position x y angle axis">
        <!-- leg position -->
        <joint name="${prefix}leg_center_joint_${side}${position}" type="fixed">
            <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
            <parent link="${prefix}body_link" />
            <child link="${prefix}leg_center_${side}${position}" />
        </joint>
        <link name="${prefix}leg_center_${side}${position}">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.0001"/>
                <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6" />
            </inertial>
        </link>
        <!-- coxa -->
        <joint name="${prefix}coxa_joint_${side}${position}" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${angle}" />
            <parent link="${prefix}leg_center_${side}${position}" />
            <child link="${prefix}coxa_${side}${position}" />
            <axis xyz="0.0 0.0 1.0" />
            <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
	    <dynamics damping="0.01" />
        </joint>
        <link name="${prefix}coxa_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
		    <mesh filename="package://jethexa_description/meshes/simplify/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.4 0.9 0.4 1" />
                </material>
            </visual>
            <collision name="coxa_collision_${side}${position}">
                <origin xyz="0.02 0.0 0.0" rpy="0.0 ${my_pi/2} 0.0" />
                <geometry>
		            <cylinder radius="0.01" length="${coxa_length}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.02 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.05"/>
                <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
            </inertial>
        </link>
        <!-- femur -->
        <joint name="${prefix}femur_joint_${side}${position}" type="revolute">
            <origin xyz="${coxa_length} 0.0 0.0" rpy="${axis*my_pi/2} 0.0 0.0" />
            <parent link="${prefix}coxa_${side}${position}" />
            <child link="${prefix}femur_${side}${position}" />
            <axis xyz="0.0 0.0 ${axis}" />
            <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
	    <dynamics damping="0.01" />
        </joint>
        <link name="${prefix}femur_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
		    <mesh filename="package://jethexa_description/meshes/simplify/${side}_femur.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.2 0.2 0.2 1" />
                </material>
            </visual>
            <collision name="femur_collision_${side}${position}">
                <origin xyz="${femur_length/2} 0.0 0.0" rpy="0.0 ${my_pi/2} 0.0" />
                <geometry>
		            <cylinder radius="0.01" length="${femur_length}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.035 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.06"/>
                <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
            </inertial>
        </link>

        <!-- tibia -->
        <xacro:property name="tibia_length" value="0.123"/>
        <joint name="${prefix}tibia_joint_${side}${position}" type="revolute">
		<origin xyz="${femur_length} 0.0 0.0" rpy="0.0 0.0 ${-axis*(my_pi/2 - 5*my_pi/180)}" />
            <parent link="${prefix}femur_${side}${position}" />
            <child link="${prefix}tibia_${side}${position}" />
            <axis xyz="0.0 0.0 ${axis}" />
            <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
	    <dynamics damping="0.01" />
        </joint>
        <link name="${prefix}tibia_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${-axis*0.08727}"/>
                <geometry>
		    <mesh filename="package://jethexa_description/meshes/simplify/${side}_tibia.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.4 0.9 0.4 1" />
                </material>
            </visual>
            <collision name="tibia_collision_${side}${position}">
                <origin xyz="${tibia_length/2} 0.0 0.0" rpy="0.0 ${my_pi/2} 0.0"/>
                <geometry>
		            <cylinder radius="0.01" length="${tibia_length}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.06 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.07"/>
                <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
            </inertial>
            <gazebo reference="${prefix}tibia_${side}${position}">
                <kp>100000.0</kp>
                <kd>150.0</kd>
                <mu1>1.5</mu1>
                <mu2>1.2</mu2>
                <maxVel>1.0</maxVel>
                <minDepth>0.001</minDepth>
                <material>Gazebo/Grey</material>
            </gazebo>
        </link>
        <!-- END -->
        <joint name="${prefix}end_joint${side}${position}" type="fixed">
	    <origin xyz="0.123 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}tibia_${side}${position}" />
            <child link="${prefix}end_${side}${position}" />
            <axis xyz="0.0 0.0 0.0" />
        </joint>
        <link name="${prefix}end_${side}${position}">
        </link>
    </xacro:macro>

    <xacro:macro name="jethexa" params="prefix parent *origin">
        <joint name="${prefix}base_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}body_link" />
            <xacro:insert_block name="origin"/>
        </joint>
        <link name="${prefix}body_link">
            <visual>
                 <!-- Revert to original mesh visual -->
	        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <!-- CORRECT THE SCALE for the simplified mesh -->
		    <mesh filename="package://jethexa_description/meshes/simplify/body.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.2 0.2 0.2 1" /> <!-- Adjust color if needed -->
                </material>
            </visual>
            <collision>
                <!-- Keep simplified collision -->
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
		    <box size="${body_length_x} ${body_length_y} 0.05"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.8"/>
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
            </inertial>
        </link>
	<joint name="${prefix}lidar_joint" type="fixed">
            <parent link="${prefix}body_link"/>
            <child link="${prefix}lidar_visual_link"/>
            <origin xyz="-0.023 0.0 0.1" rpy="0.0 0.0 0.0"/>
        </joint>

	<link name="${prefix}lidar_visual_link">
		<visual>
			<origin xyz="0.0 0.0 -0.033" rpy="0.0 0.0 1.571" />
			<geometry>
				<mesh filename="package://jethexa_description/meshes/simplify/g4.stl" scale="1.0 1.0 1.0"/>
			</geometry>
			<material name="">
                    		<color rgba="0.2 0.2 0.2 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 -0.033" rpy="0.0 0.0 1.571" />
			<geometry>
				<mesh filename="package://jethexa_description/meshes/simplify/g4.stl" scale="1.0 1.0 1.0"/>
			</geometry>
			<material name="">
                    		<color rgba="0.2 0.2 0.2 1" />
			</material>
		</collision>
		<inertial>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
			<mass value="0.1"/>
			<inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4" />
		</inertial>
	</link>

        <!-- ADDED: Gazebo LiDAR Sensor attached to the visual link -->
        <gazebo reference="${prefix}lidar_visual_link">
            <!-- Sensor definition removed to avoid conflict with jethexa.gazebo.xacro -->
        </gazebo>
        <!-- END ADDED -->

        <!-- Depth camera properties -->
        <joint name="${prefix}depth_camera_joint" type="fixed">
            <parent link="${prefix}body_link"/>
            <child link="${prefix}depth_camera_link"/>
            <origin xyz="0.062455 0.0 0.07" rpy="0.0 0.0 0.0"/>
        </joint>
        <link name="${prefix}depth_camera_link">
		<visual>
			<origin xyz="0.0 0.0 -0.015" rpy="0.0 0.0 ${my_pi/2}" />
			<geometry>
				<mesh filename="package://jethexa_description/meshes/simplify/dabai.stl" scale="1.0 1.0 1.0"/>
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 0.8 1" />
			</material>
		</visual>
		<visual>
			<origin xyz="0.0105 0.0 -0.025" rpy="0.0 0.0 ${my_pi/2}" />
			<geometry>
				<mesh filename="package://jethexa_description/meshes/simplify/dabai_len.stl" scale="1.0 1.0 1.0"/>
			</geometry>
			<material name="">
				<color rgba="0.2 0.2 0.2 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 -0.015" rpy="0.0 0.0 ${my_pi/2}" />
			<geometry>
				<mesh filename="package://jethexa_description/meshes/simplify/dabai.stl" scale="1.0 1.0 1.0"/>
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 0.8 1"/>
			</material>
		</collision>
		<inertial>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
			<mass value="0.05"/>
			<inertia ixx="1e-5" ixy="0.0" ixz="0.0" iyy="1e-5" iyz="0.0" izz="1e-5" />
		</inertial>
	</link>

    <!-- ADDED: Gazebo Depth Camera Sensor attached to the depth camera link -->
    <gazebo reference="${prefix}depth_camera_link">
        <sensor type="depth" name="jethexa_depth_camera_sensor">
            <always_on>true</always_on>
            <update_rate>20</update_rate> <!-- Adjust rate as needed -->
            <camera name="depth_cam">
                <horizontal_fov>1.047</horizontal_fov> <!-- Approx 60 degrees -->
                <image>
                    <width>320</width> <!-- Lower resolution for performance -->
                    <height>240</height>
                    <format>R8G8B8</format> <!-- Format for associated RGB image -->
                </image>
                <clip>
                    <near>0.1</near> <!-- Min depth range -->
                    <far>5.0</far> <!-- Max depth range -->
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev> <!-- Noise based on Kinect -->
                </noise>
            </camera>
            <plugin name="depth_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <!-- Plugin parameters -->
                <baseline>0.2</baseline> <!-- Baseline for stereo simulation -->
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate> <!-- Use sensor update rate -->
                <cameraName>depth_camera</cameraName> <!-- Namespace for topics -->
                <imageTopicName>/jethexa/depth_camera/rgb/image_raw</imageTopicName>
                <cameraInfoTopicName>/jethexa/depth_camera/rgb/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/jethexa/depth_camera/depth/image_raw</depthImageTopicName>
                <depthImageCameraInfoTopicName>/jethexa/depth_camera/depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudTopicName>/jethexa/depth_camera/depth/points</pointCloudTopicName>
                <frameName>${prefix}depth_camera_link</frameName> <!-- Link TF frame -->
                <pointCloudCutoff>0.1</pointCloudCutoff> <!-- Min distance for points -->
                <pointCloudCutoffMax>5.0</pointCloudCutoffMax> <!-- Max distance for points -->
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength> <!-- Will be calculated by plugin -->
                <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>
    <!-- END ADDED -->

    <!-- Instantiate the depth camera using the macro -->
    <xacro:depth_camera parent="${prefix}depth_camera_link" prefix="${prefix}">
        <!-- Define the origin of the camera relative to the parent link -->
        <origin xyz="0 0 0" rpy="0 0 0" /> 
    </xacro:depth_camera>

	<joint name="${prefix}head_pan_joint" type="revolute">
		<parent link="${prefix}body_link"/>
		<child link="${prefix}head_pan_link"/>
		<axis xyz="0.0 0.0 1.0" />
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
		<limit lower="-3.14" upper="3.14" effort="10000" velocity="100" />
	</joint>
	<link name="${prefix}head_pan_link">
	</link>
	<joint name="${prefix}head_tilt_joint" type="revolute">
		<parent link="${prefix}head_pan_link"/>
		<child link="${prefix}head_tilt_link"/>
		<axis xyz="0.0 0.0 1.0" />
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
		<limit lower="-3.14" upper="3.14" effort="10000" velocity="100" />
	</joint>
	<link name="${prefix}head_tilt_link">
	</link>


        <xacro:leg prefix="${prefix}" side="R" position="R" x="-0.093205" y="-0.05098" angle="-${my_pi*3/4}" axis="1" />
        <xacro:leg prefix="${prefix}" side="R" position="M" x="0.0" y="-0.073535" angle="-${my_pi/2}" axis="1" />
        <xacro:leg prefix="${prefix}" side="R" position="F" x="0.093205" y="-0.05098" angle="-${my_pi/4}" axis="1" />
        <xacro:leg prefix="${prefix}" side="L" position="R" x="-0.093205" y="0.05098" angle="${my_pi*3/4}" axis="-1" />
        <xacro:leg prefix="${prefix}" side="L" position="M" x="0.0" y="0.07353" angle="${my_pi/2}" axis="-1" />
        <xacro:leg prefix="${prefix}" side="L" position="F" x="0.093205" y="0.05098" angle="${my_pi/4}" axis="-1" />
    </xacro:macro>
</robot>
